name: GitHub Actions Build

on:
  workflow_dispatch:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'  
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@main

    - name: Configure build
      run: ./premake5.bat

    - name: Build
      run: |
        msbuild -m build/Ultimate-ASI-Loader-x64.sln /property:Configuration=Release /property:Platform=x64
        msbuild -m build/Ultimate-ASI-Loader-Win32.sln /property:Configuration=Release /property:Platform=Win32

    - name: Pack binaries
      run: ./release-x64.bat

    - name: Upload artifact (Win32)
      uses: actions/upload-artifact@v3
      with:
        name: Ultimate-ASI-Loader-Win32
        path: dist/Win32/dll/*

    - name: Upload artifact (x64)
      uses: actions/upload-artifact@v3
      with:
        name: Ultimate-ASI-Loader-x64
        path: dist/x64/dll/*

    - name: Get release info (Win32)
      if: |
        github.ref_name == 'master' &&
        github.event_name == 'push' &&
        github.repository == 'ThirteenAG/Ultimate-ASI-Loader'
      id: release_info_x86
      uses: cardinalby/git-get-release-action@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: Win32-latest

    - name: Upload Release (Win32)
      if: |
        github.ref_name == 'master' &&
        github.event_name == 'push' &&
        github.repository == 'ThirteenAG/Ultimate-ASI-Loader'
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        name: ${{ steps.release_info_x86.outputs.name }}
        body: ${{ steps.release_info_x86.outputs.body }}
        tag: ${{ steps.release_info_x86.outputs.tag_name }}
        artifacts: dist/Win32/zip/*.zip

    - name: Get release info (Win64)
      if: |
        github.ref_name == 'master' &&
        github.event_name == 'push' &&
        github.repository == 'ThirteenAG/Ultimate-ASI-Loader'
      id: release_info_x64
      uses: cardinalby/git-get-release-action@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: x64-latest

    - name: Upload Release (Win64)
      if: |
        github.ref_name == 'master' &&
        github.event_name == 'push' &&
        github.repository == 'ThirteenAG/Ultimate-ASI-Loader'
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        name: ${{ steps.release_info_x64.outputs.name }}
        body: ${{ steps.release_info_x64.outputs.body }}
        tag: ${{ steps.release_info_x64.outputs.tag_name }}
        artifacts: dist/x64/zip/*.zip
